### ISSUE TITLE
Pokemon hatched from Eggs moved from PKSM PokeBank Treated as being CAUGHT at Level 1

### ISSUE THREAD

**Issue by kamenrider-darkglass** [FlagBrew/PKSM#312]
I use the PKSM PokeBank to Massively transfer eggs spawned in Omega Ruby to Pokémon X and Hatch them there. Everything's fine except for the fact that when I look at the description of where I met the Pokémon I hatched: it shows date met, level met, and where, but not egg received. 

This is a very huge concern because if I plan to breed competitive Pokémon, the Pokémon being treated as being CAUGHT at level 1 would raise Red flags and I could be disqualified or banned because of this.

I am going to run some tests of trading my eggs between my Gen 6 games (X and Omega Ruby) without the PKSM PokeBank to see what happens to the "Met" description and update this thread. If the problem lies with PKSM, please fix it. I don't want to be banned for cheating since I am legitimately breeding Pokémon.    

Update - After running some tests, I have made the following discoveries:

1. Trading an egg to another game and back again and then hatching it results in:

Nature: Insert Nature Here
Egg Received: Insert date here
From: a Day-Care Couple 
Egg Hatched: Insert date here
Where: Insert location here
Characteristic: Insert here

2. Receiving an egg via trading and then hatching it results in:

Nature: Insert Nature Here
Egg *Obtained*: Insert date here
From: *Link Trade*
Egg Hatched: Insert date here
Where: Insert location here
Characteristic: Insert here

3. Moving Eggs from out of the PKSM PokeBank and then hatching them results in:

Nature: Insert Nature Here
Date Met: Insert Date Here
Where: Insert location here
Level Met: 1
Characteristic: Insert here

As you can see for number 3, any egg hatched after moving it out of the PKSM PokeBank results in it being treated as being *CAUGHT* at level 1 rather than being hatched from an egg. This makes it appear to be a hacked Pokemon even though it was bred and hatched legitimately. 

I merely use the PKSM for convenience (specifically the bank), not cheating. For someone like me who wants to compete in a Pokemon video game competition, this would get me disqualified and possibly banned. Please fix this in your next update so that Pokémon Hatched from eggs *AFTER* being moved out of the PKSM Bank would be treated as being hatched from an egg like they are supposed to be, not treated as being caught at level 1 which is obviously impossible for any Pokémon in any Pokémon Game.

**Comment by BernardoGiordano** [comment]
red flags? which version are you running?

**Comment by MattOlivoto** [comment]
I think by red flags he means that judges would see that hatched mon is a hacked mon, what would get him disqualified of the competition.

**Comment by BernardoGiordano** [comment]
I theoretically solved the problem, but I don't have a way to test. If the OP wants to, I can send a build to see if the changes fix the problem

**Comment by kamenrider-darkglass** [comment]
Update#2 - After some more testing with some free time on my hands, I've made the following additional discoveries with the current version of PKSM:

1. When depositing an egg into the PKSM bank and then withdrawing it back into the same game and *then* hatching it, the hatched Pokémon is treated as being hatched from an egg like normal. 

2. When depositing an egg into the PKSM bank and then withdrawing it into a *different* game and *then* hatching it, the hatched Pokémon is treated as having been *CAUGHT* at level 1

**Comment by kamenrider-darkglass** [comment]
Update # 2 - After doing some more testing with a little extra time on my hands, I've made the following additional discoveries:

1. When depositing an egg into the PKSM bank and then withdrawing it at a later time into the *same* game, a Pokémon hatched from this egg is treated as having been hatched from an egg like normal.

2. When depositing an egg into the PKSM bank and then withdrawing it at a later time into a *different* game, a Pokémon hatched from this egg is treated as having been CAUGHT at Level 1.

3. I tested this using Gen 6 games only. I did this using Omega Ruby Eggs and then subsequently hatching them in X and Omega Ruby. I've yet to test how eggs produced in X and Y are affected by this.

P.S. About me closing and reopening this thread; I accidentally clicked the close and comment button instead of just the comment button. Sorry about that.

**Comment by BernardoGiordano** [comment]
I asked for something important, go check that comment

**Comment by kamenrider-darkglass** [comment]
I know about that comment, that's why I wanted to do further testing to give you more information incase I missed something. I'm going to test how this affects X and Y produced eggs now.

**Comment by kamenrider-darkglass** [comment]
Update # 3 - This will be my final update as I have tested every scenario I can think of. I've also discovered something I didn't notice before and I am going to summarize all of my discoveries in this comment in the form of a report.

When eggs produced in ANY Gen 6 game (X,Y,ORAS) are deposited into the PKSM bank, the following occurs:

1. If an egg in the bank produced in one game is withdrawn into another game, the description for that egg is as follows: 

*A Mysterious Pokémon Egg that was received from Mystery Zone on 0/0/2000*

2. If that egg hatches, it will be treated as having been CAUGHT at level 1. This is bad for competitive reasons (Aegislash in a Dream Ball anyone?)  

3.  If an egg in the bank produced in one game is withdrawn back into the game it *originated* from, the above 2 does not occur. This egg will have a normal egg description and when hatched, will be treated as having been hatched from an egg like normal. It is only when that egg is hatched in a different game that it is treated as having been caught at level 1.

Now that all the information has been gathered, please develop a fix for this with this new information in mind. I just wanted to be thorough incase I missed something and it turned out I did; which were the egg description and the glitch not happening when the egg returns to its game of origin.

**Comment by deadair3210** [comment]
Wonder if it has anything to do with the games not having the other games locations names. Possibly trading normally changes the location field to something else, that and trading with PKSM does not? What causes the game to say the "Came from a far away land" for location?

**Comment by BernardoGiordano** [comment]
Try PKSM 4.2.2 (released some hours ago) to see if some of the problems you noticed are still there

**Comment by kamenrider-darkglass** [comment]
I just tried the new 4.2.2 PKSM release. Nothing has changed. Everything that was mentioned in update #3 still occurs

**Comment by Qiyao7** [comment]
So, even in 5.0, this problem still exist. Uhm...though actually egg can`t be stored in the official PM bank.  So maybe says that, ok just hatch it in the original game and send to new Gen for a competition —— No.  New problem arise is that a bug about PM handler. Why I found this is that I sent my hatched Buneary from Moon to Ultra Moon, and later found it can`t evolve even the friendship is 255 (I did not change anything through pksm). Then I found the the change occurs to the friendship of original trainer not current trainer, while the data of current trainer ID is 00 00 00 00...... . So I guess when I draw a pm form pksm storage to new game, it do nothing with the current trainer data, which cause system thought this pm is in the original trainer`s hand (change happens to friendship  Original Trainer), but the IDs are different so when judging a friendship evolution, it checks the friendship of Current Trainer (which is 0 cause no current trainer). Then I change the friendship of Current Trainer to 255 by pksm and leave the Current Trainer ID blank as before. then it evolved in the game. 

I think this is a BIG BUG of PKSM.

**Comment by BernardoGiordano** [comment]
Should be fixed by https://github.com/BernardoGiordano/PKSM/commit/934ba5f2284dc9bc2b4864f1dd12fcf76e1859f1

**Comment by Noeliel** [comment]
Issue has been closed but 934ba5f didn't actually fix it :/

**Comment by piepie62** [comment]
I believe this should be fixed in the rewrite. If not, then comment and I will reopen the issue.

**Comment by pokelector** [comment]
This is still an issue. On 6.1.1 I transferred some eggs and they were CAUGHT at level 1. In egg form they were from Mystery Zone, 0/0/2000 as opposed to "from a link trade" as they should be.

**Comment by pokelector** [comment]
https://github.com/kwsch/PKHeX/issues/2269
Same thing in PKHeX. Make of this what you will.

**Comment by pokelector** [comment]
Issue is this:
Not setting egg info to CT data. The game normallu updates a traded egg to the tid/sid of the handling trainer. PKSM keeps the TID/SID of the first person instead of updating it as should. Tapping the 'Take ownership'button manually fixes these eggs.

**Comment by BernardoGiordano** [comment]
Is this still an issue?

**Comment by Admiral-Fish** [comment]
This should be fixed as of #957 and 2fc8ff5/1e3e4ae. Note that Edit Transfer must be set to True.
